seed: 42
train:
  data: Users/abinavr/Desktop/mri_data/train/
  label: Users/abinavr/Desktop/mri_data/train/
  image_size: 192
  batch_size: 16
  num_workers: 4
  experiment_name: cyclegan_t2_generator
  checkpoint_path: ../models/
  lr: 0.001
  weight_decay: 1e-5
  epochs: 10
