seed: 42
train:
  data: /Users/abinavr/Desktop/mri_data/train/**/**/T1postcontrast
  label: /Users/abinavr/Desktop/mri_data/train/**/**/T2SPACE
  image_size: 128
  batch_size: 4
  num_workers: 0
  experiment_name: t1c_t2_generate
  checkpoint_path: /Users/abinavr/Desktop/cycleMRI/models/
  lr: 0.0001
  weight_decay: 1e-5
  epochs: 10

val:
  data: /Users/abinavr/Desktop/mri_data/val/**/**/T1postcontrast
  label: /Users/abinavr/Desktop/mri_data/val/**/**/T2SPACE

inference:
  data: /Users/abinavr/Desktop/mri_data/test/**/**/T1postcontrast
  label: /Users/abinavr/Desktop/mri_data/test/**/**/T2SPACE
  image_size: 128
  model_path: /Users/abinavr/Desktop/cycleMRI/models/generator_4_0.0001_5.pt
